# config.yaml

baseURL: https://gruendau.github.io/einfuehrung-in-swift-und-swiftui/
languageCode: de-DE
#title: Einführung in Swift und SwiftUI

# URL
# LInk: https://privat.albicker.org/blog/2017-02-03-hugo-die-plage-mit-den-urls.html
uglyURLs: true        # /admin.html
relativeURLs: false
canonifyURLs: false   # /admin/   <-- Hugo default Einstellung

# ---------------------------------------
# Site Parameter    
# --------------------------------------- 
params:
  
  head:
    title: Einführung in Swift und SwiftUI
    slogan: we love Swift!

  layout:
    fixedHeader: true
    fixedFooter: true

    # stickyHeader: true
  switches:

    # Admin
    #   Layout
    showLayoutFiles: false

    #   Hugo Variablen
    showHugoVariablesAll: false
    showHugoVariablesFile: true
    showHugoVariablesSite: true
    showHugoVariablesPage: true
    showHugoVariablesGit: true
    showHugoVariablesMenu: false
    showHugoVariablesShotcode: true
    showHugoVariablesSitemap: true
    showHugoVariablesTaxonomy: true
    showHugoVariables: true


# ---------------------------------------
# CSS   
# --------------------------------------- 
css: ["css/main.css"]

# ---------------------------------------
# Javascript   
# --------------------------------------- 
js: ["js/main.js"]


# ---------------------------------------
# Goldmark Markdown
# ---------------------------------------
# Link: https://github.com/yuin/goldmark/

# Allow HTML-Code
markup:
  goldmark:
    renderer:
      unsafe: true


# ---------------------------------------
# Git
# ---------------------------------------
enableGitInfo: true